CREATE TABLE Users
(
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Names NVARCHAR(100) NOT NULL,
Surname NVARCHAR(100) NOT NULL,
DateBH DATE NOT NULL CHECK(DateBH!>GETDATE()),
Email NVARCHAR(100) NOT NULL UNIQUE,
Telephone NVARCHAR(10) NOT NULL UNIQUE,
Position NVARCHAR(20) NOT NULL,
Passwords NVARCHAR(20) NOT NULL
)
